[package]
name = "coloc_oracle"
description = "On-chain oracle storing the CEX -> AWS colocation recommendation"
version = "0.1.0"
rust-version = "1.84.1"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "coloc_oracle"

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }

[features]
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(nightly)'] }
